export { default as AlumniDashboard } from './Alumni/Dashboard/Dashboard'; 
export { default as Login } from './Alumni/Auth/Login/Login';
export { default as ErrorPage } from './Error/Error';
export { default as LandingPage } from './Landing/LandingPage';
export { default as InstitutionLogin } from './Institution/Auth/Login/Login';
export { default as InstitutionSignup } from './Institution/Auth/signup/Signup';
export { default as InstitutionDashboard } from './Institution/dashboard/Dashboard';
export { default as ForgotPassword } from './Alumni/Auth/forgotPassword/Forgotpassword';
export { default as ChangePassword } from './Alumni/Auth/changePassword/ChangePassword';